### ISSUE TITLE
Don't have users upload TV show images

### ISSUE THREAD

**Issue by davidrunger** [tebatalla/GoodShows#5]
What user wants to do that? :) I think that the API you are planning to use might be able to provide you with images?

**Comment by tebatalla** [comment]
I wasn't sure what to label that type as. I guess since Heroku doesn't store files, it'll just have to be a url. This is related to issue #6 ultimately. If I do decide to store API info on first requests for a show, how would I store an image then, a url link?

**Comment by tebatalla** [comment]
Talked offline, images are stored as links.
