### ISSUE TITLE
Don't have shows on your own server?

### ISSUE THREAD

**Issue by davidrunger** [tebatalla/GoodShows#6]
Have you considered the possibility that you might want to make API requests directly from Backbone to your TV show API? This would cut out the middleman and make your app faster.

**Comment by tebatalla** [comment]
I talked to Ryan about this and he recommended that to make things a little faster, I could store data from the API once the first request for a TV show is ever made. However, I definitely see the benefit in just connecting straight to the API. What do you think?

**Comment by tebatalla** [comment]
Resolved offline. Search results are not stored on the server, but once a user clicks on a search result and gets taken to the show's info page, the show is then added to the app's database.
